integer:
  2

training:
  labels:
    event_cat:
      - cargo_loader
      - jet_bridge
      - belt_loader
      - catering_vehicle
      - pca
      - pushback_tug
      - pushback_tug_version2
      - belt_loader_version2
      - fueling_truck
    non_event_cat:
      - airplane
      - airplane_front
      - baggage
      - tow_tractor
      - chocks_on
      - baggage_trailer
      - chocks_off
      - fwd_cargo_door_open
      - cargo_door_opener_ladder
      - bus
      - car
      - van
      - suv
      - truck
    sel_catNms:
      - cargo_loader
      - jet_bridge
      - belt_loader
      - catering_vehicle
      - pca
      - airplane_front
      - pushback_tug
      - belt_loader_version2
      - fueling_truck
      - tow_tractor

  save_dir: datasets/9
  dataset_list:
    - train
    - test
    - val
  req_height: 720
  req_width: 1280

annotation:
  input_dir: annotation/verified
  output_dir: annotation/verified

  ann_data_correction:
    video_files:
      - video_8
    ann_label_ver: annotation_1
#    ann_save_ver: annotation_1_1

  merge_ann_data:
    video_file: video_8
    annotation_versions:
      - annotation_1
      - annotation_2

  change_yolo_ann_data:
    image_dir: rac_g23_v16
    master_dir: detection/correction_labels/input
    slave_dir: yolov5/runs/detect/exp48/labels
    save_dir: detection/correction_labels/modified
    change_ann_id:
      - 1
      - 2
      - 5

video:
  video_path: live_feed/gate_23/
  video_segment: rac_g23_video_17
  save_img_dir: images
  multiple_factor: 25
